// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBicWKnp3inpTowZmzbg4IPl5fwwKSA1xQ',
    appId: '1:925545210146:web:6f79b6ea4943afe265057b',
    messagingSenderId: '925545210146',
    projectId: 'livestream-app-32b54',
    authDomain: 'livestream-app-32b54.firebaseapp.com',
    storageBucket: 'livestream-app-32b54.firebasestorage.app',
    measurementId: 'G-X45YGFV1NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXD_ShRl4outb9Cttj1215kUfX4Ts_XZA',
    appId: '1:925545210146:android:d958655d0df50c1865057b',
    messagingSenderId: '925545210146',
    projectId: 'livestream-app-32b54',
    storageBucket: 'livestream-app-32b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFg6gQH_B06cX4kRiW07bYenrY8yfzjys',
    appId: '1:925545210146:ios:0059f4df91beecbe65057b',
    messagingSenderId: '925545210146',
    projectId: 'livestream-app-32b54',
    storageBucket: 'livestream-app-32b54.firebasestorage.app',
    iosBundleId: 'com.example.streamapp',
  );
}
